---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gemini-api-key
  namespace: ai-sre-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: gemini-api-key
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        # Name of the secret in OCI Vault
        key: gemini-api-key